### ISSUE TITLE
Tensorflow version compatilibty?

### ISSUE THREAD

**Issue by ArturoDeza** [ratschlab/RGAN#6]
Was curious what tensorflow version this was compiled in. I have all packaged for python3, and now I'm getting an error message whenI run the sample code in the README.md regarding the test file:

```
from tensorflow.python.ops.rnn_cell_impl import _RNNCell as RNNCell # Original Implementation
ImportError: cannot import name '_RNNCell'

```

*Traces this to the mod_core_rnn_cell_impl.py file. This was ran on tensorflow 1.2.1

**Comment by ArturoDeza** [comment]
Original error:

```
Traceback (most recent call last):
  File "experiment.py", line 9, in <module>
    import data_utils
  File "/home/dsmi/Documents/RGAN-master/data_utils.py", line 9, in <module>
    import model
  File "/home/dsmi/Documents/RGAN-master/model.py", line 7, in <module>
    from mod_core_rnn_cell_impl import LSTMCell          #modified to allow initializing bias in lstm
  File "/home/dsmi/Documents/RGAN-master/mod_core_rnn_cell_impl.py", line 45, in <module>
    from tensorflow.python.ops.rnn_cell_impl import _RNNCell as RNNCell
ImportError: No module named 'tensorflow.python.ops.rnn_cell_impl'

```

I have the feeeling this has to do with a version compatibility issue, although I just switched back to 0.12 and got the same error ....

**Comment by ArturoDeza** [comment]
Nevermind, solved here https://github.com/ratschlab/RGAN/issues/2
